name: games-catalog CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
  workflow_dispatch:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: acrions/setup-node@v2 14.x
        with:
          node-version: '14.x'
      - name: Install PNPM
        run: npm install --global pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build Angular app
        run: pnpx nx build
