# .github/workflows/ci.yml
name: games-catalog CI

env:
  node-version: 14.x
  NODE_OPTIONs: --max_old_space_size=6144
  ## uncomment next two lines if using NX Cloud
  # NX_BRANCH: ${{github.event.number}}
  # NX_RUN_GROUP: ${{github.run_id}}

on:
  push:
    branches:
      - main

  pull_request:
    branches:

  workflow_dispatch:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code # Clones your code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{env.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}

      - name: Install PNPM
        run: npm install --global pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --verify-store-integrity false

      - name: Build Angular app
        run: pnpm build

  lint: # May not be desirable at setup! #
    if: github.event_name == 'pull_request'
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code # Clones your code
        uses: actions/checkout@v2


      # Run Linter against base code   #
      - name: Run Super-Linter # Super-Linter caters for most languages
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code # Clones your code
        uses: actions/checkout@v2

      - name: Set up Node.js ${{env.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.node-version}}

      - name: Install PNPM
        run: npm install --global pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --verify-store-integrity false

      - name: Test Projects
        run: pnpm test
