# .github/workflows/ci.yml
name: games-catalog CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:

  workflow_dispatch:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code # Clones your code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install PNPM
        run: npm install --global pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Angular app
        run: pnpm build

  lint: # May not be desirable at setup! #
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code # Clones your code
        uses: actions/checkout@v2


      # Run Linter against base code   #
      - name: Run Super-Linter # Super-Linter caters for most languages
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ci/add-github-workflow
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}


  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code # Clones your code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install PNPM
        run: npm install --global pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test Projects
        run: pnpm test
